notifications:
    commits:      commits@commons.apache.org
    issues:       issues@commons.apache.org
    pullrequests: issues@commons.apache.org
    jira_options: link label
    jobs:         notifications@commons.apache.org
